# Generated by Django 4.2 on 2023-04-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Any company', max_length=300)),
                ('description', models.TextField(default='Any description')),
                ('city', models.CharField(default='Any city', max_length=300)),
                ('address', models.TextField(default='Somewhere in the world')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Any vacancy', max_length=300)),
                ('description', models.TextField(default='Any description')),
                ('salary', models.FloatField(default=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='api.company')),
            ],
        ),
    ]
